[project]
name = "dojo-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==2.2.6",
    "matplotlib==3.10.3",
    "pytest==8.3.4",
    "pyqt6>=6.9.0",
    "ipykernel>=6.29.5",
]
